import { Poppins } from "next/font/google";

const poppins = Poppins({weight:['400', '500', '700'] ,subsets: ["latin"] });

export const metadata = {
    title: "About",
    description: "Generated by create next app",
};

const getTime = async( ) => {
    // const res = await fetch('http://localhost:3000/time', {cache: 'no-store'})
    const res = await fetch('http://localhost:3000/time', {next: {revalidate: 5}})
    const data = await res.json()
    return data.currentTime
}

const AboutPage =async () => {
    const currentTime = await getTime()
    return (
        <div className={`${poppins.className}`}>
            <h1>About Page</h1>
            <h3>Time:{currentTime} </h3>
        </div>
    );
};

export default AboutPage;